// actions
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'
export const CREATE_POST_DOCUMENT_SUCCESS = 'CREATE_POST_DOCUMENT_SUCCESS'
export const UPDATE_POST_DOCUMENT_SUCCESS = 'UPDATE_POST_DOCUMENT_SUCCESS'
export const DELETE_POST_DOCUMENT_SUCCESS = 'DELETE_POST_DOCUMENT_SUCCESS'
export const SAVE_POST_DOCUMENT_VOTE_SUCCESS = 'SAVE_POST_DOCUMENT_VOTE_SUCCESS'
export const LOGIN_REQUEST = ''
export const LOGIN_SUCCESS = ''
export const LOGIN_FAILURE = ''
export const LOGOUT_REQUEST = ''
export const LOGOUT_SUCCESS = ''
export const LOCK_SUCCESS = ''
export const LOCK_ERROR = ''
export const SHOW_LOCK = ''

// flags
export const POST_MODE_READ = 'POST_MODE_READ'
export const POST_MODE_EDIT = 'POST_MODE_EDIT'

// other
export const VOTE_UP = 'VOTE_UP'
export const VOTE_DOWN = 'VOTE_DOWN'
